### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by 19wintersp**
Basic Rust Cargo build action

### CODE REVIEW

**Comment by cursorweb** [comment]
Looks good, but would you mind adding some tests?

**Comment by 19wintersp** [comment]
@cursorweb Unit tests, or to run the examples in the test/ directory?

**Comment by cursorweb** [comment]
unit tests probably

**Comment by 19wintersp** [comment]
@cursorweb You can add tests the way you'll normally do it with `cargo`, the action is set up to run `cargo test` after successful builds. As for adding the actual tests, I'll probably address that in another PR, though make sure to add them as you go along

**Comment by cursorweb** [comment]
alright, i'll merge.

**Pull request merged**
