### PR TITLE
Made CLI Better

### PR DESCRIPTION
**Pull request by SpicySpices**
Created `cli.rs` to store CLI commands and parsing arguments passed.

### CODE REVIEW

**Comment by 19wintersp** [comment]
Would it not be easier to use a pre-built parsing library, like [clap](https://crates.io/crates/clap)?

**Comment by SpicySpices** [comment]
I haven't heard of clap, but I can look into it and try rewriting the CLI using it.

**Comment by 19wintersp** [comment]
@SpicySpices I was already working on doing that, but sounds good :ok_hand:

**Comment by SpicySpices** [comment]
Ah go ahead, it seems like you have more experience than me at it

**Pull request closed without merging**
